import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Space_Grotesk } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"], // choose subsets
  variable: "--font-space-grotesk", // optional: for CSS variable
  weight: ["400", "500", "700"], // pick weights you need
});

// Poppins setup
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "600", "700"], // pick weights you need
});


export const metadata: Metadata = {
  title: "Shayog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${spaceGrotesk.variable}  ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
